### ISSUE TITLE
User Story: About Page

### ISSUE THREAD

**Issue by Humanslaughter** [Humanslaughter/pp4-blog#10]
Epic: #11 

As a **User** I can **click the About link** so that **I can read about the blog**

### Acceptance Criteria

- A visible About text will show when the About link is clicked.

As a **Admin** I can **create or update content on the About page** so that **users can read about my blog**

### Acceptance Criteria

- The About Page is visible in the admin panel.

### Tasks

- [x] Create About Page App.
- [x] Integrate About Link in User Interface.
- [x] Implement About Page Display.
- [x] Design Admin Panel Section for About Page.
- [x] Integrate Admin Panel Link for About Page.
- [x] Implement Content Creation/Update Functionality.
- [x] Verify About Page Visibility in Admin Panel.
- [x] Test About Link and Page Display.
- [x] Test Admin Content Creation and Update.
