### ISSUE TITLE
User Story: Delete Posts

### ISSUE THREAD

**Issue by Humanslaughter** [Humanslaughter/pp4-blog#18]
Epic: #11 

As a **Admin** I can **delete posts** so that **I can remove any post I don't like**

### Acceptance Criteria

- A logged-in user can delete blog posts.

### Tasks

- [x] Design Delete Post Confirmation.
- [x] Implement Post Deletion Backend.
- [x] Integrate Post Deletion Frontend.
- [x] Test Post Deletion Functionality.
