### ISSUE TITLE
User Story: Read Posts

### ISSUE THREAD

**Issue by Humanslaughter** [Humanslaughter/pp4-blog#2]
Epic: #11 

As a **User** I can **click a post** so that **I can read the text fully**

### Acceptance Criteria

- A detailed view of a post can be seen when a post title is clicked.

### Tasks

- [x] - Design Post Detail Page.
- [x] - Implement Frontend Click Functionality.
- [x] - Fetch and Display Post Content.
- [x] - Test Click-to-Read Functionality.
