### ISSUE TITLE
User Story: Mark Collaboration Requests As Read

### ISSUE THREAD

**Issue by Humanslaughter** [Humanslaughter/pp4-blog#21]
Epic: #11 

As a **Site Owner** I can **mark collaboration requests as "read"** so that **I can see how many I still need to process**

### Acceptance Criteria

- A "Read" Field is available for collaboration requests.
- Clicking "Read" updates the request status to "read".

### Tasks

- [x] - Implement "Read" Field.
- [x] - Update Request Status in the Database.
- [x] - Test "Read" Field Functionality.
- [x] - Ensure Accessibility and Usability.
