### ISSUE TITLE
User Story: Account Registration

### ISSUE THREAD

**Issue by Humanslaughter** [Humanslaughter/pp4-blog#4]
Epic: #14 

As a **User** I can **register an account** so that **I can leave comments on posts**

### Acceptance Criteria

- A user can register an account.
- Then the user can log in.
- When the user is logged in they can comment on posts.

### Tasks

- [x] Design and implement the Registration Form.
- [x] Implement Sign Up, Sign In, and Sign Out functionality.
- [x] Implement Commenting for logged in users.
- [x] Test functionality.
