### ISSUE TITLE
User Story: Comment Approval

### ISSUE THREAD

**Issue by Humanslaughter** [Humanslaughter/pp4-blog#9]
Epic: #13 

As a **Admin** I can **approve or disapprove a comment** so that **I can manage and remove unpleasant comments**

### Acceptance Criteria

- A logged-in user can approve comments.
- A logged-in user can disapprove comments.

### Tasks

- [x] Implement Approve Field.
- [x] Implement Backend Logic for Comment Approval.
- [x] Integrate Approval Functionality into Frontend.
- [x] Test Comment Approval functionality.
